// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWK6FMGOU1oYKPiFITQ5JE1O2Nd-feLEA',
    appId: '1:926630747739:web:b25cb0bbec93dc108ce97e',
    messagingSenderId: '926630747739',
    projectId: 'chatbot-ce96f',
    authDomain: 'chatbot-ce96f.firebaseapp.com',
    storageBucket: 'chatbot-ce96f.firebasestorage.app',
    measurementId: 'G-T364NQM95C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLwjMHxoikRaWY8QHaaFtas8O35y9vNVU',
    appId: '1:926630747739:android:7647afdb3587d0818ce97e',
    messagingSenderId: '926630747739',
    projectId: 'chatbot-ce96f',
    storageBucket: 'chatbot-ce96f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdJn3tue8p7dcPkmg_2_lED0ZHu2ZGFP8',
    appId: '1:926630747739:ios:00e47f524afdbc868ce97e',
    messagingSenderId: '926630747739',
    projectId: 'chatbot-ce96f',
    storageBucket: 'chatbot-ce96f.firebasestorage.app',
    iosBundleId: 'com.example.iassistente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdJn3tue8p7dcPkmg_2_lED0ZHu2ZGFP8',
    appId: '1:926630747739:ios:00e47f524afdbc868ce97e',
    messagingSenderId: '926630747739',
    projectId: 'chatbot-ce96f',
    storageBucket: 'chatbot-ce96f.firebasestorage.app',
    iosBundleId: 'com.example.iassistente',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWK6FMGOU1oYKPiFITQ5JE1O2Nd-feLEA',
    appId: '1:926630747739:web:e87a61de85b1f4038ce97e',
    messagingSenderId: '926630747739',
    projectId: 'chatbot-ce96f',
    authDomain: 'chatbot-ce96f.firebaseapp.com',
    storageBucket: 'chatbot-ce96f.firebasestorage.app',
    measurementId: 'G-LMFVTW8FHF',
  );
}
